"""Single source of truth for generated service + case-study pages."""

SERVICES = [
    {
        "slug": "ai-consulting",
        "service_type": "AI consulting and development",
        "name": "AI Consulting & Development",
        "promise": "Strategic AI integration and custom models built to solve one specific business problem — not to chase a trend.",
        "deliverables": [
            "An honest assessment of where AI helps your business and where it doesn't.",
            "Custom models and integrations wired into the tools your team already uses.",
            "Retrieval, automation, and agent workflows scoped to a measurable outcome.",
            "Evaluation and guardrails so the system stays reliable in production.",
        ],
        "who_for": "Teams sitting on data or manual workflows who want a concrete AI result, not a research project.",
        "related": ["packship"],
    },
    {
        "slug": "custom-software",
        "service_type": "Custom software development",
        "name": "Custom Software Development",
        "promise": "Tailored software designed around your business requirements — and built to scale as you grow.",
        "deliverables": [
            "Discovery that maps the real problem before a line of code is written.",
            "Software built to your workflow, not forced onto an off-the-shelf tool.",
            "Clean, documented code your team can own and maintain.",
            "Production support after launch, not a hand-off at the finish line.",
        ],
        "who_for": "Founders and teams whose process has outgrown spreadsheets and SaaS workarounds.",
        "related": ["restaurant-ordering-portal", "packship"],
    },
    {
        "slug": "web-mobile",
        "service_type": "Web and mobile app development",
        "name": "Web & Mobile Development",
        "promise": "Responsive websites and applications built with technologies your team can actually maintain.",
        "deliverables": [
            "Fast, accessible, responsive front-ends that work on every device.",
            "Native-quality mobile apps for iOS and Android.",
            "SEO and performance built in from the first commit.",
            "A maintainable codebase in a stack your team can hire for.",
        ],
        "who_for": "Businesses that need a site or app that performs — and doesn't rot the day it ships.",
        "related": ["new-york-fine-foods", "new-york-mobile-mechanic", "packship"],
    },
    {
        "slug": "cloud",
        "service_type": "Cloud infrastructure",
        "name": "Cloud Solutions",
        "promise": "Scalable, secure cloud infrastructure that stays predictable as your traffic grows.",
        "deliverables": [
            "Cloud architecture sized to your load and your budget.",
            "Automated deployment pipelines and infrastructure-as-code.",
            "Security, backups, and monitoring configured from day one.",
            "Cost controls so the bill scales with revenue, not surprises.",
        ],
        "who_for": "Teams moving off fragile hosting or bracing for a growth curve.",
        "related": ["packship", "restaurant-ordering-portal"],
    },
    {
        "slug": "it-infrastructure",
        "service_type": "IT infrastructure and security",
        "name": "IT Infrastructure",
        "promise": "Server, network, firewall, and security work for businesses that simply need uptime.",
        "deliverables": [
            "Network, server, and firewall setup done properly the first time.",
            "Security hardening and patch management.",
            "Monitoring and alerting so problems surface before customers notice.",
            "Documentation and support your team can rely on.",
        ],
        "who_for": "Small businesses without an in-house IT team who can't afford downtime.",
        "related": [],
    },
    {
        "slug": "data-intelligence",
        "service_type": "Data intelligence and analytics",
        "name": "Data Intelligence",
        "promise": "Analytics, visualization, and migration work that turns raw data into a decision.",
        "deliverables": [
            "Data pipelines that consolidate scattered sources into one clean model.",
            "Dashboards and visualization your team will actually use.",
            "Migrations handled without losing history or breaking downstream tools.",
            "Reporting that answers the question you're actually asking.",
        ],
        "who_for": "Teams drowning in data they can't turn into answers.",
        "related": ["rwd-pipeline"],
    },
]

CASE_STUDIES = [
    {
        "slug": "packship",
        "bespoke": True,  # hand-built page; build.py must not overwrite it
        "image": "packship.jpg",
        "name": "PackShip",
        "meta": "2026 · Mobile · iOS App",
        "stack": ["React Native", "TypeScript", "JavaScript", "Three.js", "Postgres", "Redis"],
        "live_url": "https://apps.apple.com/app/id6754204899",
        "live_label": "View on the App Store",
        "brief": "Shipping is guesswork for most people: which box, how much it will cost, which carrier. PackShip set out to answer all three from a single photo.",
        "built": "An AI-powered iOS app that sizes items from a photo, fits them into the right box with a real-time 3D packing view, and compares live UPS, FedEx, and USPS rates side by side. Built on React Native with a Postgres and Redis backend for fast rate lookups.",
        "outcome": "Shipped to the App Store as a consumer product, turning a multi-step, error-prone task into one photo and a tap.",
        "related_services": ["ai-consulting", "web-mobile"],
    },
    {
        "slug": "foodtruckrentals",
        "name": "Food Truck Rentals",
        "image": "foodtruckrentals.jpg",
        "meta": "2026 · Web · Client Site",
        "stack": ["TypeScript", "Next.js 16", "React 19", "Tailwind CSS", "Motion", "Technical SEO"],
        "live_url": "https://www.foodtruckrentals.com",
        "live_label": "Visit the live site",
        "brief": "A New York brand-activation company wraps, staffs, and permits food trucks for fashion houses, department stores, and restaurants \u2014 and was selling all of it without a site of its own.",
        "built": "A 24-page Next.js 16 site built around the work itself: a full-bleed activation hero, a truck roster that animates on a variable-width axis, and a page for every way a truck gets rented \u2014 weddings, product launches, film production, corporate events, ice cream, coffee carts, and the tri-state markets. Every commercial page carries JSON-LD Service, FAQ, and LocalBusiness data generated from one pricing module, so published prices cannot drift from the page. Keyword research shapes the URL structure, and a Vitest suite of 119 tests guards it \u2014 including one that fails the build if two pages start competing for the same keyword cluster.",
        "outcome": "A live national site, indexed and structured to compete beyond its first city: the flagship URL now targets a 12,100/mo search term rather than the 320/mo local qualifier it launched on.",
        "media": [
            ("foodtruckrentals-home.jpg", "Home page \u2014 the activation hero, with the roster of wrapped trucks alongside."),
            ("foodtruckrentals-work.jpg", "The work index \u2014 every activation, with the client, the borough, and the year."),
        ],
        "related_services": ["web-mobile", "data-intelligence"],
    },
    {
        "slug": "new-york-fine-foods",
        "image": "nyff.jpg",
        "name": "New York Fine Foods",
        "meta": "2026 · Web · Client Site",
        "stack": ["TypeScript", "Next.js", "JavaScript"],
        "live_url": "https://www.newyorkfinefoods.com",
        "live_label": "Visit the live site",
        "brief": "A NYC catering, pizza-truck, and mobile-bar brand needed a site as memorable as its events.",
        "built": "A cinematic Next.js site with full-bleed motion, media galleries, service menus, and booking inquiries, designed to make a first impression and convert it into a booking.",
        "outcome": "A live brand site that turns browsers into event inquiries.",
        "related_services": ["web-mobile"],
    },
    {
        "slug": "new-york-mobile-mechanic",
        "bespoke": True,  # hand-built page; build.py must not overwrite it
        "image": "nymm.jpg",
        "name": "New York Mobile Mechanic",
        "meta": "2026 · Web · Client Site",
        "stack": ["TypeScript", "Next.js", "Tailwind CSS", "Framer Motion"],
        "live_url": "https://www.newyorkmobilemechanic.com",
        "live_label": "Visit the live site",
        "brief": "A 24/7 mobile mechanic competing for urgent, high-intent repair searches across NYC.",
        "built": "A high-energy Next.js site with animated stat gauges that count up, clear service breakdowns, live Google reviews, and one-tap call-to-book, with local SEO built to rank for on-demand repair searches across the city.",
        "outcome": "A conversion-focused site engineered to capture same-day repair demand.",
        "related_services": ["web-mobile"],
    },
    {
        "slug": "delivery-routing",
        "name": "Delivery routing platform",
        "image": "delivery-routing.jpg",
        "meta": "2026 \u00b7 Web App \u00b7 Logistics",
        "stack": ["Python", "FastAPI", "OR-Tools", "React", "TypeScript", "SQLite", "Fly.io"],
        "brief": "A home medical equipment provider planned every delivery day by hand: one dispatcher, a messy export of the day\u2019s tickets, six vans, and drivers waiting to leave.",
        "built": "A dispatch app that runs the whole morning in four steps. It parses the delivery log and refuses to invent anything it cannot read confidently \u2014 an unreadable row becomes a flagged task, never a guess. It applies the business rules the dispatcher used to hold in their head (per-driver caps, town bans, delivery windows, driver and vehicle eligibility), then solves for minimum drive time with Google OR-Tools against live traffic. Geocoding fails closed, and a per-solve travel-matrix budget makes a runaway maps bill structurally impossible rather than merely unlikely. The output is a printed cut sheet designed for a clipboard and a pen, plus an Excel and CSV log for the office. 1,278 tests cover the rules.",
        "outcome": "Upload to printed routes in minutes, with every ticket accounted for \u2014 in daily production use, deployed on Fly.io. Client details are withheld; the screenshots below run on synthetic data.",
        "media": [
            ("delivery-routing-routes.jpg", "Solved routes \u2014 six drivers, colour-matched to the map, with any stop movable between them."),
            ("delivery-routing-review.jpg", "Review & fix \u2014 47 tickets on the sheet, one flagged rather than guessed at."),
            ("delivery-routing-export.jpg", "Export \u2014 printable driver cut sheets for the van, Excel and CSV for the office."),
        ],
        "related_services": ["custom-software", "data-intelligence"],
    },
    {
        "slug": "vintus",
        "image": "vintus.jpg",
        "name": "Vintus",
        "meta": "2026 · Web · E-commerce",
        "stack": ["WordPress", "PHP", "Python"],
        "live_url": "https://vintus.com",
        "live_label": "Visit the live site",
        "brief": "A leading wine importer needed e-commerce that could handle a large, structured catalog and the operations behind it.",
        "built": "An e-commerce platform with inventory management, order processing, and customer-relationship tools, built on WordPress and PHP with Python services behind the scenes.",
        "outcome": "A production storefront running a national wine import catalog.",
        "related_services": ["custom-software", "web-mobile"],
    },
    {
        "slug": "restaurant-ordering-portal",
        "image": "pizzeria.jpg",
        "name": "Restaurant ordering portal",
        "meta": "2026 · Web · Product",
        "stack": ["TypeScript", "Square SDK", "Delivery APIs"],
        "live_url": "https://pizzeria-software.vercel.app",
        "live_label": "Visit the live demo",
        "brief": "Third-party delivery apps charge restaurants punishing commissions on every order. This product removes the middleman.",
        "built": "Commission-free online ordering that plugs into a restaurant's existing Square POS. Orders, payments, and SMS updates flow through with no third-party fees skimming the check.",
        "outcome": "A working ordering portal that lets restaurants keep the full value of every order.",
        "related_services": ["custom-software", "cloud"],
    },
    {
        "slug": "rwd-pipeline",
        "image": "rwd-pipeline.jpg",
        "name": "Real-World Data Pipeline",
        "meta": "Product · Data · 0→1",
        "stack": ["Product Management", "Agile", "Planning"],
        "live_url": "https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fneuragul.com%2Fassets%2Fdocs%2Frwd-pipeline-portfolio.pptx",
        "live_label": "View the case-study deck",
        "brief": "Early cancer detection depends on messy, inconsistent real-world data from dozens of sources.",
        "built": "Led Product Management at Freenome for a 0→1 ETL pipeline that standardized diverse real-world data into a single Common Data Model, the foundation downstream research and models depend on.",
        "outcome": "A 0→1 data pipeline delivered from concept to production.",
        "related_services": ["data-intelligence"],
    },
    {
        "slug": "landscape-drainage-proz",
        "image": "landscapedrainage.jpg",
        "name": "Landscape Drainage Proz",
        "meta": "2026 · Web · Shopify",
        "stack": ["Shopify", "Custom Liquid", "SEO", "Google Ads"],
        "live_url": "https://landscapedrainageproz.com",
        "live_label": "Visit the live site",
        "brief": "A drainage-products retailer wanted more than a storefront — they wanted sales.",
        "built": "A Shopify storefront buildout paired with conversion and marketing work: CTA design and implementation, Google Ads, and an SEO and marketing strategy that compounded over time.",
        "outcome": "Tripled the client's online sales.",
        "related_services": ["web-mobile", "data-intelligence"],
    },
]
